#include "header.h"

using namespace std;

class Solution {
public:
    int findBlackPixel(vector< string >& picture, int N) {
        if (picture.size() == 0) return 0;
        if (picture[0].size() == 0) return 0;
        vector<int> colQty(picture[0].size(), 0);
        vector<long long int> colVal(picture[0].size(), 0);
        vector<int> rowQty(picture.size() , 0);
        vector<long long int> rowVal(picture.size() , 0);
        int ii = 1;
        for(size_t i = 0 ; i < picture.size() ; ++i){
            int jj = 1;
            for (size_t j = 0 ; j < picture[0].size() ; ++j){
                if (picture[i][j] == 'B') {
                    rowQty[i] ++;
                    // rowVal[i] += jj;
                    colQty[j] ++;
                    // colVal[j] +=ii;
                }
                // jj*=2;
            }
            // ii *= 2;
        }
        // for (auto s : colVal) cout << s << " ";
        // cout << endl;
        // for (auto s : colQty)  cout << s<< " ";
        // cout << endl;
        // int i = 0;
        // for (auto s : rowVal) {
        //     cout << s << "  " << rowQty[i++] <<  endl;
        //
        // }
        int result = 0;
        for(size_t i = 0 ; i < rowVal.size() ; ++i){
            for (size_t j = 0 ; j < colVal.size() ; ++j){
                if ( rowQty[i] == N && rowQty[i] == colQty[j] ){
                    int target = -1;
                    int k = 0;
                    bool find = true;
                    while (find && k != rowQty.size()){
                        if (target == -1 ){
                            if (picture[k][j] == 'B') target = k;
                            else {
                                k++;
                                continue;
                            }
                        }else {
                            k++;
                            continue;
                        }
                        if (picture[k][j] == 'B'){
                            for (size_t z = 0 ; z < colVal.size() ; ++z){
                                if (picture[target][z] != picture[k][z]) {
                                    find = false;
                                    break;
                                }
                            }
                        }
                        k++;
                    }
                    if (find) result ++;

                }
            }
        }
        return result;

    }
};

int main(){
    Solution s;
    vector<int> nums = {0,1,2};
    vector<int> nums2 = {2,3,6,};
    string str1 = "abab";
    string str2 = "cat dog cat dog";
    vector< string > picture = {"WWWWWBWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBWWWWWWWWWW", "BWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWBWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBWWWWWWWWWW", "WWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWBWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBWWWWWWWWWW", "WWWWWWWWWWWWWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBWWWWWWWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWBWWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "BWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "BWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBBWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWBWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWW", "WWWWWWWBWWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWBWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWBWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWBWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWBWWWWWWWWWBWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWBWWWWWWWWWBWWWWWWBWWWWWWWW", "WWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBWWWWWWBWWWWWWBWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWW", "WWWWWBWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWW", "WWWWWWWWWWWWWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWBWWWWWWWWWBWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWBWWWWWWWWWBWWWWWWBWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "BWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWBWWWWWWWWWBWWWWWWBWWWWWWWW", "WWWWWWWBWWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBBWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "BWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWBWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWBWWWWWWWWWWWWWWWWWW", "WWWWWBWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWW", "WWWWWWWBWWWWWWWWWWBWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWW", "WWWWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWBWWBWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWW", "WWWWWBWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWBWBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBBWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWBWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWBBWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "WWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWBWW", "WWWWWBWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWBWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWBWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWW", "WWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWBWBWWWWWWWWWWWWWWWWWWWWWW", "WWWWWWWWBWWWWWWWWWWWWBWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWBWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWBWWWWWWWW", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWBWWWWWWBWWWWWW", "WWWWWBWWWWWWWWBWWWWWWBWWWWWWWWWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBWWWWWWWWWWWWW"};
    // cout << s.merge(nums, 6, nums2, 3) << endl;

    cout << (s.findBlackPixel(picture , 5));

}
